word: bulalll
words: 你,我,他

eureka:
  instance:
#      instanceId:
      hostname: localhost
#      prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: base-service
  rabbitmq:
#    host: localhost
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
server:
  port: 8091  
management:
  security:
    enabled : false
endpoints:
  restart:
    enabled: true
    sensitive: false 

