word: bulajiubula
eureka:
  instance:
#      instanceId:
      hostname: localhost
#      prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: base-service
server:
  port: 8091  
