

server:
  port: 8090

#  port: ${PORT:${SERVER_PORT:0}}
#  这个的意思是随机指定个没使用的端口

spring:
  application:
    name: user-service
  rabbitmq:
#    host: localhost
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
  datasource:
#    url: jdbc:mysql://192.168.99.100:3306/test
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    max-active: 8
    max-wai: -1
    max-idle: 8
    min-idle: 0
    timeout: 0
    
endpoints:
  restart:
    enabled: true
    sensitive: false 
    
    
